#define NDS32_ISA_DIV
#define NDS32_ISA_MAC_EXT
#define NDS32_ISA_16B_EXT
#define NDS32_ISA_PERF_EXT
#define NDS32_ISA_PERF2_EXT
#define NDS32_ISA_STRING_EXT
#define NDS32_ISA_BASELINE_V3
#define NDS32_ISA_DX_REGS
#define NDS32_ISA_AUDIO_EXT
#define NDS32_ISA_AUDIO_CONFIG 32
#define NDS32_ISA_COP_EXT
#define NDS32_ISA_IFC_EXT
#define NDS32_ISA_EX9_EXT
